### PR TITLE
Use standard cordova PACKAGE_NAME variable in place of applicationId

### PR DESCRIPTION
**Pull request by cfsnyder**
Standard variable for this is documented here: https://cordova.apache.org/docs/en/4.0.0/plugin_ref/spec.html#$package_name

### CODE REVIEW

**Comment by macdonst** [comment]
@cfsnyder this works and it's a valid way to fix the issue but I'm wondering if we need to merge it as what's there isn't broken and in the new Cordova-Android they add the same fix so we won't need the push.gradle file soon.

https://github.com/apache/cordova-android/commit/fb9cf60c4100d5bc6f9320747611da1ca0ced289

So what benefit does merging this PR give us? I'm not being sarcastic, I'm asking seriously.

**Comment by cfsnyder** [comment]
@macdonst the current push.gradle solution wasn't working in our build process, for whatever reason. I came a across the standard $PACKAGE_NAME variable, found that it fixed my issue and was simpler than the current approach, so I thought I'd submit a PR to suggest the change. If others aren't having issues with the push.gradle solution and Cordova-Android is adding the same fix, I agree that it isn't necessary for you to merge this.

**Comment by macdonst** [comment]
@cfsnyder how are you building? Gradle is the future of all the Android stuff.

**Comment by cfsnyder** [comment]
@macdonst we're using the standard gulp-cordova plugins to initiate the build with a gulp task, which means we are using the gradle build system implicitly. I'm not sure if push.gradle was never being run or it may be possible that its output was being overwritten by another stage of the build process. I would have to dive into it further to be sure.

**Comment by macdonst** [comment]
@cfsnyder I'm not going to merge this but I do appreciate the pull request. Can you send me more info on your build process as it may be something I can help fix in Gulp Cordova.

**Comment by macdonst** [comment]
@cfsnyder well as it turns out this change looks like it will fix #481 so I will be merging.

**Comment by cfsnyder** [comment]
@macdonst great glad it could be used.

**Comment by macdonst** [comment]
@cfsnyder yeah, it works around a bug in plugman so why not :)

Thanks again for the submission!

**Pull request merged**
