### PR TITLE
Possible fix for hybrid notification payloads on Android with possible solution for deleting notifications.

### PR DESCRIPTION
**Pull request by Moghul**
Added a class that handles background notifications for notifications that come in "notification" payload instead of "data" payload.
## Description

Added a new class that extends GcmReceiver. The code for it is a mirror copy of the GCMIntentService class with the minor difference of adding a context and using it since it's not an Action.

Also added a function to the same class that can delete a notification if the value "delete" : notificationID is present in the "data" payload on Android.
## Related Issue

#897 

## Motivation and Context

Solves 2 issues: Notification deletion on Android and background notifications on Android.
## How Has This Been Tested?

Pushed notifications for the app while it was
1) Closed completely
2) Closed but present in the recent apps screen
3) Open and in the foreground

Pushed notifications with delete keys where the value was the notId of a still available notification.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fredgalvao** [comment]
Why did you delete `<framework src="push.gradle" custom="true" type="gradleReference" />` from `plugin.xml`?

**Comment by Moghul** [comment]
@fredgalvao That was a slight oversight, sorry. The build environment I am using can't handle Gradle so I removed the file and its references and replaced ${application} with my own app ID. I changed the latter back for the push but I forgot about the reference...
See #883 
Of course, feel free to re-add it.

**Comment by fredgalvao** [comment]
@Moghul I see. I think we can leave solving the build process on XDK to issue #883, but that's just my opinion.

Regardless, @macdonst 's words will probably be the final ones.

**Comment by Moghul** [comment]
@fredgalvao Of course. As for #883, the "fix" wasn't supposed to be in here. Preferably, the guys at Intel would solve it themselves. This was just something I needed for myself.

**Comment by macdonst** [comment]
@Moghul can you rebase this PR with master and fix the plugin.xml issue and re-submit? Shouldn't need to touch every line in plugin.xml.

**Comment by Moghul** [comment]
See #941

**Pull request closed without merging**
