### PR TITLE
Remove the setting applicationId code

### PR DESCRIPTION
**Pull request by jcesarmobile**
## Description

applicationId is set since cordova-android 5.1.0, so this code is not needed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
@jcesarmobile push.gradle is getting pretty small now 😄

**Comment by jcesarmobile** [comment]
what is the multiDexEnabled for? maybe you can also remove it

**Comment by macdonst** [comment]
It fixes a problem when the app includes more than 64k methods.

**Comment by jcesarmobile** [comment]
then maybe we should move that to cordova-android? or let the user handle it? 
why should the plugin worry about that?

**Comment by macdonst** [comment]
You know what, I should make it a plugin of it's own for now.

>

**Comment by fredgalvao** [comment]
A plugin for 5 lines of code: npm, what have you done to mankind?

**Comment by jcesarmobile** [comment]
I think it's a good idea

**Comment by macdonst** [comment]
@jcesarmobile did it!

**Comment by jcesarmobile** [comment]
I really just meant it to be an independent plugin, but not a dependency of push plugin. Or do the FCM libs always cause the app to have more than 64k methods?

**Pull request merged**
