### PR TITLE
Add getApplicationIconBadgeNumber method

### PR DESCRIPTION
**Pull request by rubenstolk**

### CODE REVIEW

**Comment by macdonst** [comment]
Seems legit but can you update the readme with instructions on the new method.

**Comment by rubenstolk** [comment]
@macdonst I think you were a bit faster than me because I was still doing that :) Amended the commit

**Comment by macdonst** [comment]
@rubenstolk lemme know when you are done.

**Comment by rubenstolk** [comment]
@macdonst It's done now.

**Comment by macdonst** [comment]
@rubenstolk great stuff, thanks.

**Pull request merged**
