### PR TITLE
V1.x Android: handle dismissed notifications

### PR DESCRIPTION
**Pull request by NitroGhost**
## Description

When a user dismisses notifications, you would expect them to go away. Currently when using Inbox style, previous notifications will be included, even though the user has dismissed the notification. This fix handles dismissed notifications, and clears the internal list.
## Related Issue

#1665

## Motivation and Context

With the related issue, originally the dismissal of the notification would result in the app opening which is obviously the incorrect way to handle this, but the "fix" applied was just to remove the deleteIntent altogether, which is also the incorrect way to handle this.
## How Has This Been Tested?

I sent a bunch of inbox style notifications with the same notId, dismissed the notification, then resent a bunch more. Checked to see if the previous dismissed notifications were gone. They were.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fredgalvao** [comment]
Doesn't this go against some common cases of conversation/threaded applications? Such as:

- Maria sends you "Hey"
- Maria sends you "What's up"
- You dismiss the single inbox-style notification that had those two messages
- Maria sends you "Call me back"
- ?

At this point, most applications would bring back the 2 you dismissed (as they actually weren't processed, just dismissed/delayed), agregate the third one, and present the user a new inbox-style notification with all 3 of them.

The interpretation of what `dismissing a notification` means is subjective, I know, and multiple scenarios would argue to both sides, and thus I'd say we have to at least let the user decide instead of assume.

**Comment by fredgalvao** [comment]
Also, we might need to bring whatever is decided here to the master branch too.

**Comment by macdonst** [comment]
@fredgalvao this PR deals with Inbox style notifications not Android N groupings. When you dismiss an inbox style notification all of the notifications should be dismissed from the plugin as they are only contained in one notification. In Andoid N they can be expanded to have multiple lines in the notification center. 

This also fixes the `setDeleteIntent` problem. This is a good basis for either fire the `notification` event with `dismissed = true` or adding a new `dismissed` event.

**Comment by fredgalvao** [comment]
I should've read the related issue at full before commenting. Nevermind my daydreams.

**Comment by NitroGhost** [comment]
Would you like me to do a v2.x pull request also for this?

**Comment by macdonst** [comment]
@NitroGhost nope, I was doing a cherry-pick and my computer crashed. Should be committed soon.

**Comment by NitroGhost** [comment]
that's great 😁

**Comment by macdonst** [comment]
@NitroGhost harsh! You are happy my computer crashed 😉

**Comment by macdonst** [comment]
@NitroGhost merged into v2.x

**Pull request merged**
