### PR TITLE
[Android] Added launchMode to PushHandlerActivity

### PR DESCRIPTION
**Pull request by coderReview**
If not present cordova will add it automatically and we might end with two entries for PushHandlerActivity in AndroidManifest.xml.

### CODE REVIEW

**Comment by macdonst** [comment]
@coderReview what problem does this address? Just wondering what I should be testing here.

**Comment by coderReview** [comment]
I have the following plugins:

<pre>
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-network-information",
    "phonegap-plugin-push",
    {
      "locator": "https://github.com/coderReview/SalesforceMobileSDK-CordovaPlugin.git",
      "id": "com.salesforce"
    },
    {
      "locator": "https://github.com/VitaliiBlagodir/cordova-plugin-datepicker.git",
      "id": "cordova-plugin-datepicker"
    },
    {
      "locator": "https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git",
      "id": "cordova-plugin-x-toast"
    }
</pre>

In the end I get two entries in AndroidManifest.xml file for PushHandlerActivity. The cordova lib automatically add the launchMode to the activity entry. 
Changing from:

``
<activity android:exported="true" android:name="com.adobe.phonegap.push.PushHandlerActivity" />
``
to
``
<activity android:exported="true" android:launchMode="singleTop" android:name="com.adobe.phonegap.push.PushHandlerActivity" />
``

However, when I install Salesforce plugin which depends on phonegap-plugin-push, the plugin.xml has the activity defined without launchMode. So cordova adds the PushHandlerActivity line again to AndroidManifest.xml file.

**Comment by coderReview** [comment]
@macdonst Any comments on that? A different launchMode could be set if necessary.

**Comment by macdonst** [comment]
@coderReview I noticed you made some changes on the Salesforce plugin? Does this change still need to be merged?

**Comment by coderReview** [comment]
I haven't test the latest version of the Salesforce plugin. They are making some changes to allow the plugin to be built correctly in Android platform. I will wait until that is ready to be able to test and see if the issue mentioned in this pull request is fixed or not.

**Comment by feda8891** [comment]
Hi all,
I have the same issue. Has been resolved?

Thanks

**Comment by macdonst** [comment]
@coderReview any updates?

**Comment by coderReview** [comment]
@macdonst give me a couple of days to check. I was busy with other activities.

**Pull request closed without merging**
