### PR TITLE
Add dependency on cordova-support-google-services

### PR DESCRIPTION
**Pull request by chemerisuk**
Adding dependency on [cordova-support-google-services](https://github.com/chemerisuk/cordova-support-google-services) should resolve some conflicts.

## Description
Per our discussion at https://github.com/chemerisuk/cordova-support-google-services/issues/1#issuecomment-377402542. 

## Related Issue
https://github.com/chemerisuk/cordova-support-google-services/issues/1

## Motivation and Context
Solve compatibility issues between cordova plugins.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by chemerisuk** [comment]
@macdonst let me know if I can help to update documentation.

**Comment by macdonst** [comment]
@chemerisuk thanks for the PR. I just merged it in. We should try and get as many people as possible to move to using your plugin as a dependency. Actually, we should probably make it an option you can enabled in `cordova-android`.

**Comment by chemerisuk** [comment]
@macdonst agree, It's hard to imagine modern Android development without having a dependency on google services. The advantage of gradle plugins is that they do not add extra code at runtime, so people that for a some reason do not have `google-services.json` won't notice any difference.

The only issue is compatibility with many existing plugins... On the other hand recent `cordova-android 7` breaks plugins anyway, so may be it's a good to to integrate `cordova-support-google-services` into the core. Thoughts?

**Comment by fredgalvao** [comment]
@chemerisuk You should try and spread that word on the cordova dev mailing list. We'll get broader opinions there.

**Comment by macdonst** [comment]
I agree with @fredgalvao, we should bring this to the cordova dev mailing list. What I envision is a preference like:

```
<preference name="android-RunGoogleServicesPlugin" value="true"/>
```

where the default it is `false`. Then any app that needs the plugin to run will enable this preference. 

Say this lands in cordova-android 8 then @chemerisuk can update the `cordova-support-google-services` so it only installs in an app when cordova-android is less than 8. That way plugin devs who use the `cordova-support-google-services` won't even need to update their plugin.xml files.

Also, @chemerisuk what do you mean by cordova-android 7 breaks plugins?

**Comment by chemerisuk** [comment]
@macdonst folder structure has changed and in many cases plugins must be updated because of that (read http://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html#disqus_thread).

As for preference `android-RunGoogleServicesPlugin` - it totally makes sense. I was thinking first about always adding the gradle plugin (because it doesn't add any runtime code), but after testing on empty project it seems like the gradle plugin fails without `google-services.json`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /.../git/test/platforms/android/app/src/nullnull/debug/google-services.json
  /.../git/test/platforms/android/app/src/debug/nullnull/google-services.json
  /.../git/test/platforms/android/app/src/nullnull/google-services.json
  /.../git/test/platforms/android/app/src/debug/google-services.json
  /.../git/test/platforms/android/app/src/nullnullDebug/google-services.json
  /.../git/test/platforms/android/app/google-services.json
```

**Comment by macdonst** [comment]
@chemerisuk I just sent a message out to the dev mailing list. Please chime in.

**Comment by chemerisuk** [comment]
@macdonst I have issue with connecting to that discussion... The only suggestion is to drop `android-` prefix from the preference name - it seems like new cordova preferences use only case case style, may be better to be consistent. Something like `RunGoogleServicesPlugin` or `EnableGoogleServicesPlugin`.

**Comment by macdonst** [comment]
@chemerisuk sorry are you saying you can't participate in the discussion? With regards to the exact name of the preference I'm not worried about what it eventually gets called.

**Comment by chemerisuk** [comment]
@macdonst had problems with authentication, now resolved.

**Comment by chemerisuk** [comment]
@macdonst  Just submitted PR at https://github.com/apache/cordova-android/pull/438

**Pull request merged**
