### PR TITLE
Use framework and call register only when needed

### PR DESCRIPTION
**Pull request by t-nonque**

### CODE REVIEW

**Comment by macdonst** [comment]
@t-nonque please re-submit the PR without the changes to plugin.xml and the deletion of android-support-v13.jar. I can't merge those changes until PhoneGap Build supports building Android projects via Gradle. This is why PR #26 isn't merged.

I will merge the change to GCMRegistrar if you re-send the PR.

**Comment by felquis** [comment]
Hi,
This PR works and also fix these build errors http://cl.ly/image/350g1w2W0A1D & http://cl.ly/image/1I0y0j1v3Z05

**Comment by macdonst** [comment]
@felquis Yes, I know but I can't merge it because the plugin will stop working on PhoneGap Build.

**Comment by fredgalvao** [comment]
This should be applicable now, just need to rebase the commits so that only PushPlugin.java gets modified (because the framework thing has [been fixed](https://github.com/phonegap/phonegap-plugin-push/commit/6b5bebb85c94cca0a734c743b37a50fccc57c8c7)).

**Comment by macdonst** [comment]
I'm moving to the new way of doing things for GCM so this PR won't be valid in the near future.

https://developers.google.com/instance-id/guides/android-implementation

**Pull request closed without merging**
