### PR TITLE
Possible fix for hybrid notification payloads on Android with possible solution for deleting notifications.

### PR DESCRIPTION
**Pull request by Moghul**
Added a class that can handle 'notification' payloads on Android.
Added a function that can handle 'delete' : notID values in the payload on Android to the GcmIntentService class.
## Description

Sending a push notification with the notification information (title, message,etc) in the 'notification' payload should now allow the 'data' payload to be sent to the app when it's in the background or closed on ANDROID.

Sending a 'delete' : notID in the 'data' payload should delete a notification with the correct 'notID' present in the notification tray on ANDROID.
## Related Issue

#897 
Requested redo of #904 
## Motivation and Context

With GCM, on iOS, the presence of 'notification' payload is required to see any notification in the notification tray.
On Android, the presence of the 'notification' payload, means that 'data' payload is not sent to the app.
This fixes the issue of needing two server implementations for creating push notification payloads: One iOS and one Android.
## How Has This Been Tested?

Sent push with the payloads below with Postman.
For adding a notification:
```
{   
    "priority" : "high",
    "notification" : {
        "title": "Test Notification",
        "body": "This notification has a body",
        "notId": 10
    },
    "data" : {
        "someDataHere": "some information here",
        "content-available": "1"
    },
    "to": "gcm reg id here"
}
```
For deleting a notification:
```
{ 
    "priority" : "high",
    "notification" : {},
    "data": {
    "delete" : 10
},
  "to" : "gcm reg id here"
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
@Moghul you don't have to close and open new PR's you can just update the code in the PR for future notice. 

I don't think I can merge this in as is. It really needs more testing. One scenario I found I was able to crash the app was by sending [picture type messages](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#picture-messages) to the plugin using your code. Can you do some more testing with the various payload types?

Also, I'm a little worried that Google recommends the GcmReceiver do nothing and the GcmListenerService is where the work should be done.

**Comment by Moghul** [comment]
Sorry, I don't really have the time to do more testing. The code for the new class is the same as yours. Pretty much nothing is changed apart from where I get my contexts.

It's also possible that Google recommends that but 'notification' payloads break your implementation of the 'notification' event : nothing triggers in the app on Android.

I'm sure the solution is somewhere in the middle but this was made for work and right now I don't have the spare time to develop it.

If you don't want or can't work with this, at least you know that a GcmReceiver class is a good start.

**Comment by macdonst** [comment]
@Moghul okay, thanks for your contribution. Like I said I can't merge as is because of the crash I found. If this is going to be a solution it would be better off for the Receiver to pass everything to the Listener but Google doesn't seem to make that easy.

**Comment by macdonst** [comment]
@Moghul also, I know the "notification" payload breaks things. Google even documents that if you send the data across as "notification" then the OS handles everything for you. That's why all of the docs and samples use "data" instead.

**Comment by Moghul** [comment]
@macdonst yeah, that's great, but if you want GCM on iOS, you either have to make 2 different payloads for the two platforms or do something with the Receiver on Android.

**Comment by macdonst** [comment]
@Moghul yeah, because Google were jerks (yeah, I said it) when they implemented this wacky way.

**Comment by Moghul** [comment]
@macdonst oh I am NOT disagreeing.

**Comment by macdonst** [comment]
Sorry, I can't merge this in. I'll take another look at this in the FCM branch.

**Pull request closed without merging**
