### PR TITLE
➕Update cordova-support-google-services to 1.2.0, change default value for FCM_VERSION

### PR DESCRIPTION
**Pull request by chemerisuk**
## Description
Motivation for the changes described at https://github.com/phonegap/phonegap-plugin-push/issues/2423

## Related Issue

https://github.com/phonegap/phonegap-plugin-push/issues/2423

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by chemerisuk** [comment]
@macdonst In order to avoid compatibility issues I recommend to include those changes into at least major release.

**Comment by macdonst** [comment]
@chemerisuk yes, I think the next version of this plugin will be a v3. Not only these changes but switching over to UNUserNotification for iOS and probably adding a method to dismiss single notifications. I think that justifies a major version bump.

**Comment by chemerisuk** [comment]
👍

**Comment by macdonst** [comment]
@chemerisuk thanks for the PR. I'm trying to get to the v3 tasks this week.

**Pull request merged**
