### PR TITLE
Support Twilio Notify

### PR DESCRIPTION
**Pull request by viktormuller**
## Description
Adds support for Twilio Notify on Android. Specifically adds following mappings to normalizeKey:
- twi_body --> message
- twi_title --> title
- twi_sound --> sound

## Motivation and Context
Twilio Notify allows developers to send notifications to iOS and Android devices without worrying about the target platform. This change allows developers to use this Phonegap plugin to write unified cross-platform (iOS and Android) code to receive messages. Together Notify and the Phonegap plugin allows building truly cross-platform notification systems with a single unified code-base both on client and service side.

## How Has This Been Tested?
We have tested it with a [cross-platform ionic app](https://www.twilio.com/console/notify/early-access?code=NotifyJacobs2016) that we have demonstrated at Jacobshack 2016. 

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
@viktormuller looks good to me. Can you write up a short blurb to include in PAYLOAD.md?

**Comment by viktormuller** [comment]
@macdonst Sure, i will do that and add it to the PR.

**Comment by viktormuller** [comment]
@macdonst Added some description to PAYLOAD.md. Let me know if that makes or if you have any suggestions for improvement.

**Comment by macdonst** [comment]
@viktormuller thanks for the commit and updating the docs!

**Comment by viktormuller** [comment]
@macdonst No problem thanks for the help and the quick merge.

**Pull request merged**
