### PR TITLE
fix issue #41

### LINKED ISSUE #41: iOS doesn't add foreground key
Android sets `additionalData.foreground: true` on notification data when the app is open. This is helpful because background notifications - in most apps - when tapped will go to a route... but if the app is open  we will likely alert the user in a different manner instead of route them away from where they are.

Is this not 100% necessary for iOS too? Maybe i'm missing another way to achieve the same thing?

### PR DESCRIPTION
**Pull request by Deminetix**
This fixed #41 and adds a foreground boolean the same as on Android

### CODE REVIEW

**Comment by macdonst** [comment]
@Deminetix can you modify your fix so that is sets foreground to true when isInline is true and sets foreground to false when isInline is false. Then I'll test your PR and merge.

**Comment by Deminetix** [comment]
@macdonst i'm not sure i follow. What was the original intention of the isInline variable?

**Comment by macdonst** [comment]
I don't even think we need to be this fancy. The 'notificationReceived' method only gets called when the app is the the foreground.

**Comment by macdonst** [comment]
@Deminetix okay, I merged this in but I will do the quick addition to set foreground to false myself. 

I really appreciate you stepping up to help out with this plugin. Finally a minor point, check out Chris' slides on commit messages. Something like this PR could be rebased so it is all one commit instead of 3.

https://github.com/CSilivestru/git-different

**Pull request merged**
