### PR TITLE
Support Library Fix

### PR DESCRIPTION
**Pull request by keab42**
Switching the reference to the support library to use the framework tag and removing the support library jar from the libs folder.

This should prevent the multiple dex issues that appear when you use this plugin with others that also depend on the support libraries.

### CODE REVIEW

**Comment by macdonst** [comment]
@keab42 Thanks, I'll try it out later today.

**Comment by macdonst** [comment]
@keab42 How did you get this to compile? I get gradle issues where it conflicts with the min SDK version declared by Cordova Android?

**Comment by keab42** [comment]
Ah I had a manual edit locally in the Manifest.xml to bump that min-version up. Would you like me to add that to the PR?

**Comment by macdonst** [comment]
@keab42 I had to fix an issue in phonegap-start and cordova-android as the min sdk version should be 14 not 10 (or 7 as it was in one case). I'm going to hold off on pulling this request in until cordova-android 4.0.3 is released. That way people won't have to edit the AndroidManifest.xml file in the platforms/android folder.

Sound reasonable?

**Comment by keab42** [comment]
Sounds good. 

Cordova for Android is driving me nuts at the moment, hopefully 4.0.3 will be more stable and work better with Gradle.

**Comment by macdonst** [comment]
@keab42 Yeah, Joe and I were talking about it. Hoping to get a release out soonish.

**Comment by Hirbod** [comment]
I have FacebookSDK (which also includes support-v13) installed and I tried your fix, but when I remove the support lib, I'll get errors.
```
/Users/Hirbod/Desktop/appdev/Oktoberfest/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:139: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
```

If I leave it like it is, I get:

```
	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

What can I do to get this run?

**Comment by Hirbod** [comment]
Any news on this? I stuck. Can't compile Android since I've installed this plugin. Everything works well on iOS, I hoped for some answers, as my app needs to go online soon.

**Comment by slorber** [comment]
After installing this plugin, I also got this:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by fredgalvao** [comment]
*[tip]* This can be closed now, @macdonst

**Comment by macdonst** [comment]
I'm closing this one as the same change has been merged in master.

**Pull request closed without merging**
