### PR TITLE
Big text style for Android

### PR DESCRIPTION
**Pull request by FernandoMedin**

### CODE REVIEW

**Comment by fredgalvao** [comment]
+1 on this.

**Comment by ricardocarvalh0** [comment]
+1

**Comment by macdonst** [comment]
@FernandoMedin hey sorry, I did not see this sooner. It wasn't attached to an issue so I missed out on it. Can you rebase and update your PR so it merges cleanly?

**Comment by macdonst** [comment]
@FernandoMedin thanks for the PR, I ended up using it as the basis for this commit:

https://github.com/phonegap/phonegap-plugin-push/commit/56682f6a951e5d31ac1b16e96ccdb271ca6b9595

**Comment by FernandoMedin** [comment]
@macdonst, Hey! Sorry I didn't answer! I was a little bit busy and I didn't see that. Btw, thanks for the reply and the update! xD

**Pull request closed without merging**
