### PR TITLE
fix(android): bump play dep

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
## Description
Build broke today, changing this fixes it.
I have no idea why but I thought this might be useful for others.

## Related Issue

https://github.com/phonegap/phonegap-plugin-push/issues/1591 but then v11 to v12 

## Motivation and Context

Fixes our build so I thought it might be useful for others.

## How Has This Been Tested?

Before change --> app instant crashes
After change --> app works fine

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

I think this should only be a bug fix

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
Thanks @AdriVanHoudt

**Comment by jacquesdev** [comment]
@macdonst - any chance you can publish this update to npm?

**Comment by macdonst** [comment]
@AdriVanHoudt & @jacquesdev I just published a 1.10.7 version of the plugin which includes the change.

**Comment by AdriVanHoudt** [comment]
Awesome!

**Comment by macdonst** [comment]
I was on conference or airplane wifi since last week so it was hard to keep up.

**Comment by jacquesdev** [comment]
I have a feeling something has changed again :(

I am getting this error:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzx;

**Comment by macdonst** [comment]
@jacquesdev possibly. Dependency issues are becoming a major pain these days. If different plugins are using different versions of they play services or support libraries you can run into these issues. 

Not sure if you saw but they officially put GCM into deprecation and it will go away in 1 year. Probably a smart bet to upgrade to v2 of this plugin as soon as possible as their should be less headaches.

**Comment by jacquesdev** [comment]
@macdonst - looks like this issue is also on the latest version of the plugin 2.2.2 :( I was testing on 1.11.0 and it's essentially doing the same thing.

**Pull request merged**
