### PR TITLE
:penguin: Disable sound for Android notification channel

### PR DESCRIPTION
**Pull request by larrybahr**
Disable sound for Android notification channel

## Description
Allow sounds to be disabled for Android notifications channels

## Related Issue
https://github.com/phonegap/phonegap-plugin-push/issues/2452

## Motivation and Context
I need to send push notifications that do not play sound on Android 8+

## How Has This Been Tested?
I created a channel for that should play the default sound, the ringtone, a custom sound, and no sound.
They all worked.
I also ran the npm tests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by larrybahr** [comment]
@macdonst @jcesarmobile is there anything I can do to get this pull request merged? I need this feature for a project and it would be great if I could use the real package rather than my github repo.

**Comment by dobrevnikolay** [comment]
Hey, @larrybahr, I tried to add the plugin from your repo and it seems that it's not working for me, my app struggles to initialize it says PushNotification is not defined

**Comment by larrybahr** [comment]
@dobrevnikolay Did you see that error at build time from Cordova or at run time in the browser console? Does the original repo work for you if you try to use that?
It looks like it is working for me still. I will try to look into it more later today.

**Comment by dobrevnikolay** [comment]
@larrybahr  No need I think I figure out what the issue is and it is my mistake. However, I tried to connect you on linkedin with more questions, could you accept me if you are available for?

**Comment by larrybahr** [comment]
Glad you got it working! I accepted your LinkedIn request, but if it is a question about this commit then it is best to ask here so others can benefit from the knowledge.

**Comment by larrybahr** [comment]
@fredgalvao any idea when someone will have a chance to review or merge this pull request? I understand that you may be busy with other things. I am just trying to get a timeline for when I can revert my code from linking to my repo back to the main npm package.

**Comment by larrybahr** [comment]
@fredgalvao Thank you for helping point me in the right direction!

**Pull request merged**
