### PR TITLE
fix for entitlements requirement by ios

### PR DESCRIPTION
**Pull request by frederikbosch**
This works with cordova cli 6.4.0 and cordova ios 4.3.0.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@macdonst If you could create a branch v1.8.x I can create a PR against that branch.

**Comment by frederikbosch** [comment]
You should release this as 1.8.5. Then you buy yourself time to get PGB to work with 1.9.x and there is no need to hurry anymore.

**Comment by jcesarmobile** [comment]
I think the PGB problem is fixed

**Comment by macdonst** [comment]
@frederikbosch can you check to see if 1.9.x now works on PGB? If not I will look at publishing a 1.8.5 for everyone with this PR.

**Comment by frederikbosch** [comment]
@macdonst Will check later today. Thanks for the work any how.

**Comment by CookieCookson** [comment]
@macdonst I was just about to open a PR about this for the v2.x branch. Could it be merged into this too or should I open up a separate PR? (https://github.com/CookieCookson/phonegap-plugin-push/tree/patch-1)

**Comment by macdonst** [comment]
@CookieCookson check out `v2.0.x` as I believe I've fixed my merge screw up.

**Pull request closed without merging**
